apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-backend
  namespace: default
  labels:
    app: gateway-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-backend
  template:
    metadata:
      labels:
        app: gateway-backend
    spec:
      containers:
        - name: gateway-backend
          image: artifacts.toucanint.com/tou-rtp-gateway/dev:tag
          ports:
            - containerPort: 8082
      imagePullSecrets:
        - name: jfrog-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: gateway-backend
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30226
