apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-backend
  namespace: default
  labels:
    app: kyc-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyc-backend
  template:
    metadata:
      labels:
        app: kyc-backend
    spec:
      containers:
        - name: kyc-backend
          image: artifacts.toucanint.com/tou-rtp-kyc/dev:tag
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: jfrog-secret
---
apiVersion: v1
kind: Service
metadata:
  name: kyc-backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: kyc-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30222
