spring:
  application:
    name: tourtpgateway

  cloud:
    gateway:
      routes:            
        - id: tourtpcore-service
          uri: http://localhost:8083
          predicates:
            - Path=/toucan/core/**
          filters:
           - AuthenticationFilter
          
        - id: tourtptrs-service
          uri: http://192.168.61.101:30224
          predicates:
            - Path=/toucan/trs/**
          filters:
            - AuthenticationFilter

  data:
    mongodb:
      uri: mongodb://localhost:27017/Rtp


server:
  port: 8082

jwt:
  secret: 638CBE3A90E0303BF3808F40F95A7F02A24B4B5D029C954CF553F79E9EF1DC0384BE681C249F1223F6B55AA21DC070914834CA22C8DD98E14A872CA010091ACC
